export class newdto {
  // @ts-ignore
  decriptions: string;
  // @ts-ignore
  title: string;
  // @ts-ignore
  job_requirements: string;
  // @ts-ignore
  quanlity: number;
  // @ts-ignore
  position: string;
  // @ts-ignore
  salary: string;
  // @ts-ignore
  image: string;
  // @ts-ignore
  work_loaction: string;
  // @ts-ignore
  degree: string;
  // @ts-ignore
  major: string;
  // @ts-ignore
  working_time: string;
  // @ts-ignore
  benefit: string;
  // @ts-ignore
  id_account: number;
  // @ts-ignore
  id_category: number;
  // @ts-ignore
  type_of_work: string;
  // @ts-ignore
  sex: string;
  // @ts-ignore
  profile_language: string;
  // @ts-ignore
  profile_requirement: string;
  // @ts-ignore
  name_nd: string;
  // @ts-ignore
  phone: string;
  // @ts-ignore
  address_nd: string;
  // @ts-ignore
  email_nd: string;
  // @ts-ignore
  status: boolean
  // @ts-ignore
  create_date: Date;
}
